

# ===============================
# DATABASE CONFIGURATION
# ===============================
spring.datasource.url=jdbc:mysql://Codestream.in:3306/cs_mart
spring.datasource.username=codestream_dev_team
spring.datasource.password=Codestream@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate dialect (optional for MySQL, but safe to keep)
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

file.upload-dir=C:/Dms_new_project/DMS_Backend/uploaded-Images-fold/

# ===============================
# HIKARI CONNECTION POOL SETTINGS
# ===============================

# Max lifetime of a connection before Hikari replaces it (5 minutes)
spring.datasource.hikari.max-lifetime=300000

# Connection idle timeout (1 minute)
spring.datasource.hikari.idle-timeout=60000

# How often validation fails should timeout (3 seconds)
spring.datasource.hikari.validation-timeout=3000

# Minimum idle connections Hikari keeps
spring.datasource.hikari.minimum-idle=2

# Maximum number of connections
spring.datasource.hikari.maximum-pool-size=10

# Increase upload limits to 20 MB
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=20MB

# Tomcat upload body limits
server.tomcat.max-swallow-size=20971520
server.tomcat.max-http-post-size=20971520

#To disable automatic conversion of Column names to snake_case.
# Hibernate automatically converts any naming convention to snake_case.
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

